#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 15 13:17:15 2022

@author: etudiant
"""

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QPushButton, QVBoxLayout, QGroupBox, QWidget, QHBoxLayout
from PyQt5.QtWidgets import QMenu, QAction, QTextEdit, QMenuBar, QToolBar, QGridLayout, QLineEdit, QMessageBox, QInputDialog
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import QSize


IP = ""


class Interface(QMainWindow):
    
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Terminal")
        self.resize(600,600)
        self.group72 = QGroupBox()
        self.grid = QGridLayout()
        self.verticale = QVBoxLayout(self.group72)
        self.baroutils = QToolBar()
        self.IP = QLabel(IP)
        self.etat = QLabel("off")
        if IP != "":
            self.etat.setText("on")
        self.commande = QTextEdit()
        self.commande.setStyleSheet("color: white; background: rgba(56, 4, 40, 0.9)")
        self.reponse = QTextEdit()
        self.reponse.setStyleSheet("color: white; background: rgba(56, 4, 40, 0.9)")
        self.reponse.setReadOnly(True)
        for i in range(11):
            vide = self.creervide()
            self.baroutils.addAction(vide)
        
        self.off = QAction(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/off.png"),"OFF",self)
        self.off.setStatusTip("OFF")
        self.baroutils.addAction(self.off)
        self.baroutils.setIconSize(QSize(39,39))
        self.envoyer = QPushButton("Envoyer")
        self.envoyer.setFixedSize(110,30)
        self.grid.addWidget(self.etat, 0, 0)
        self.grid.addWidget(self.IP,0,1)
        self.grid.addWidget(self.envoyer,0,4)
        self.verticale.addLayout(self.grid)
        self.verticale.addWidget(self.commande)
        self.verticale.addWidget(self.reponse)
        
        
        self.addToolBar(self.baroutils)
        self.setCentralWidget(self.group72)
        
    def creervide(self):
        self.vide = QAction(QIcon(""),"",self)
        return self.vide
            
class Supervision(QMainWindow):
    
    
    def __init__(self,nb_pc = 24):
        super().__init__()
        self.setWindowTitle("Supervision")
        self.resize(800,800)
        self.setWindowIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/logo.png"))
        self.group = QGroupBox()
        self.grid = QGridLayout(self.group)
        
        
        self.l1 = QLabel("PC1 | IP = 192.168.56.1")
        self.b1 = QPushButton()
        self.b1.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b1.setIconSize(QSize(110,110))
        self.b1.clicked.connect(self.page)
        self.l1b1 = QVBoxLayout(self.group)
        self.l1b1.addWidget(self.l1)
        self.l1b1.addWidget(self.b1)
        self.l2 = QLabel("PC2 | IP = 192.168.56.1")
        self.b2 = QPushButton()
        self.b2.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b2.setIconSize(QSize(110,110))
        self.b2.clicked.connect(self.page)
        self.l2b2 = QVBoxLayout(self.group)
        self.l2b2.addWidget(self.l2)
        self.l2b2.addWidget(self.b2)
        self.l3 = QLabel("PC3 | IP = 192.168.56.1")
        self.b3 = QPushButton()
        self.b3.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b3.setIconSize(QSize(110,110))
        self.b3.clicked.connect(self.page)
        self.l3b3 = QVBoxLayout(self.group)
        self.l3b3.addWidget(self.l3)
        self.l3b3.addWidget(self.b3)
        self.l4 = QLabel("PC4 | IP = 192.168.56.1")
        self.b4 = QPushButton()
        self.b4.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b4.setIconSize(QSize(110,110))
        self.b4.clicked.connect(self.page)
        self.l4b4 = QVBoxLayout(self.group)
        self.l4b4.addWidget(self.l4)
        self.l4b4.addWidget(self.b4)
        self.l5 = QLabel("PC5 | IP = 192.168.56.1")
        self.b5 = QPushButton()
        self.b5.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b5.setIconSize(QSize(110,110))
        self.b5.clicked.connect(self.page)
        self.l5b5 = QVBoxLayout(self.group)
        self.l5b5.addWidget(self.l5)
        self.l5b5.addWidget(self.b5)
        self.l6 = QLabel("PC6 | IP = 192.168.56.1")
        self.b6 = QPushButton()
        self.b6.setIcon(QIcon("/home/etudiant/Téléchargements/SA-302-main/supervision/interfaces/images/pc.png"))
        self.b6.setIconSize(QSize(110,110))
        self.b6.clicked.connect(self.page)
        self.l6b6 = QVBoxLayout(self.group)
        self.l6b6.addWidget(self.l6)
        self.l6b6.addWidget(self.b6)
        self.l7 = QLabel("PC7 | IP = 192.168.56.1")
        self.b7 = QPushButton()
        self.b7.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b7.setIconSize(QSize(110,110))
        self.b7.clicked.connect(self.page)
        self.l7b7 = QVBoxLayout(self.group)
        self.l7b7.addWidget(self.l7)
        self.l7b7.addWidget(self.b7)
        self.l8 = QLabel("PC8 | IP = 192.168.56.1")
        self.b8 = QPushButton()
        self.b8.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b8.setIconSize(QSize(110,110))
        self.b8.clicked.connect(self.page)
        self.l8b8 = QVBoxLayout(self.group)
        self.l8b8.addWidget(self.l8)
        self.l8b8.addWidget(self.b8)
        self.l9 = QLabel("PC9 | IP = 192.168.56.1")
        self.b9 = QPushButton()
        self.b9.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b9.setIconSize(QSize(110,110))
        self.b9.clicked.connect(self.page)
        self.l9b9 = QVBoxLayout(self.group)
        self.l9b9.addWidget(self.l9)
        self.l9b9.addWidget(self.b9)
        self.l10 = QLabel("PC10 | IP = 192.168.56.1")
        self.b10 = QPushButton()
        self.b10.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b10.setIconSize(QSize(110,110))
        self.b10.clicked.connect(self.page)
        self.l10b10 = QVBoxLayout(self.group)
        self.l10b10.addWidget(self.l10)
        self.l10b10.addWidget(self.b10)
        self.l11 = QLabel("PC11 | IP = 192.168.56.1")
        self.b11 = QPushButton()
        self.b11.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b11.setIconSize(QSize(110,110))
        self.b11.clicked.connect(self.page)
        self.l11b11 = QVBoxLayout(self.group)
        self.l11b11.addWidget(self.l11)
        self.l11b11.addWidget(self.b11)
        self.l12 = QLabel("PC12 | IP = 192.168.56.1")
        self.b12 = QPushButton()
        self.b12.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b12.setIconSize(QSize(110,110))
        self.b12.clicked.connect(self.page)
        self.l12b12 = QVBoxLayout(self.group)
        self.l12b12.addWidget(self.l12)
        self.l12b12.addWidget(self.b12)
        self.l13 = QLabel("PC13 | IP = 192.168.56.1")
        self.b13 = QPushButton()
        self.b13.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b13.setIconSize(QSize(110,110))
        self.b13.clicked.connect(self.page)
        self.l13b13 = QVBoxLayout(self.group)
        self.l13b13.addWidget(self.l13)
        self.l13b13.addWidget(self.b13)
        self.l14 = QLabel("PC14 | IP = 192.168.56.1")
        self.b14 = QPushButton()
        self.b14.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b14.setIconSize(QSize(110,110))
        self.b14.clicked.connect(self.page)
        self.l14b14 = QVBoxLayout(self.group)
        self.l14b14.addWidget(self.l14)
        self.l14b14.addWidget(self.b14)
        self.l15 = QLabel("PC15 | IP = 192.168.56.1")
        self.b15 = QPushButton()
        self.b15.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b15.setIconSize(QSize(110,110))
        self.b15.clicked.connect(self.page)
        self.l15b15 = QVBoxLayout(self.group)
        self.l15b15.addWidget(self.l15)
        self.l15b15.addWidget(self.b15)
        self.l16 = QLabel("PC16 | IP = 192.168.56.1")
        self.b16 = QPushButton()
        self.b16.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b16.setIconSize(QSize(110,110))
        self.b16.clicked.connect(self.page)
        self.l16b16 = QVBoxLayout(self.group)
        self.l16b16.addWidget(self.l16)
        self.l16b16.addWidget(self.b16)
        self.l17 = QLabel("PC17 | IP = 192.168.56.1")
        self.b17 = QPushButton()
        self.b17.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b17.setIconSize(QSize(110,110))
        self.b17.clicked.connect(self.page)
        self.l17b17 = QVBoxLayout(self.group)
        self.l17b17.addWidget(self.l17)
        self.l17b17.addWidget(self.b17)
        self.l18 = QLabel("PC18 | IP = 192.168.56.1")
        self.b18 = QPushButton()
        self.b18.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b18.setIconSize(QSize(110,110))
        self.b18.clicked.connect(self.page)
        self.l18b18 = QVBoxLayout(self.group)
        self.l18b18.addWidget(self.l18)
        self.l18b18.addWidget(self.b18)
        self.l19 = QLabel("PC19 | IP = 192.168.56.1")
        self.b19 = QPushButton()
        self.b19.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b19.setIconSize(QSize(110,110))
        self.b19.clicked.connect(self.page)
        self.l19b19 = QVBoxLayout(self.group)
        self.l19b19.addWidget(self.l19)
        self.l19b19.addWidget(self.b19)
        self.l20 = QLabel("PC20 | IP = 192.168.56.1")
        self.b20 = QPushButton()
        self.b20.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b20.setIconSize(QSize(110,110))
        self.b20.clicked.connect(self.page)
        self.l20b20 = QVBoxLayout(self.group)
        self.l20b20.addWidget(self.l20)
        self.l20b20.addWidget(self.b20)
        self.l21 = QLabel("PC21 | IP = 192.168.56.1")
        self.b21 = QPushButton()
        self.b21.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b21.setIconSize(QSize(110,110))
        self.b21.clicked.connect(self.page)
        self.l21b21 = QVBoxLayout(self.group)
        self.l21b21.addWidget(self.l21)
        self.l21b21.addWidget(self.b21)
        self.l22 = QLabel("PC22 | IP = 192.168.56.1")
        self.b22 = QPushButton()
        self.b22.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b22.setIconSize(QSize(110,110))
        self.b22.clicked.connect(self.page)
        self.l22b22 = QVBoxLayout(self.group)
        self.l22b22.addWidget(self.l22)
        self.l22b22.addWidget(self.b22)
        self.l23 = QLabel("PC23 | IP = 192.168.56.1")
        self.b23 = QPushButton()
        self.b23.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b23.setIconSize(QSize(110,110))
        self.b23.clicked.connect(self.page)
        self.l23b23 = QVBoxLayout(self.group)
        self.l23b23.addWidget(self.l23)
        self.l23b23.addWidget(self.b23)
        self.l24 = QLabel("PC24 | IP = 192.168.56.1")
        self.b24 = QPushButton()
        self.b24.setIcon(QIcon("/home/etudiant/SA-302/supervision/interfaces/images/pc.png"))
        self.b24.setIconSize(QSize(110,110))
        self.b24.clicked.connect(self.page)
        self.l24b24 = QVBoxLayout(self.group)
        self.l24b24.addWidget(self.l24)
        self.l24b24.addWidget(self.b24)
        
        self.grid.addLayout(self.l1b1, 0, 0)
        self.grid.addLayout(self.l2b2, 0, 1)
        self.grid.addLayout(self.l3b3, 0, 2)
        self.grid.addLayout(self.l4b4, 0, 3)
        self.grid.addLayout(self.l5b5, 1, 0)
        self.grid.addLayout(self.l6b6, 1, 1)
        self.grid.addLayout(self.l7b7, 1, 2)
        self.grid.addLayout(self.l8b8, 1, 3)
        self.grid.addLayout(self.l9b9, 2, 0)
        self.grid.addLayout(self.l10b10, 2, 1)
        self.grid.addLayout(self.l11b11, 2, 2)
        self.grid.addLayout(self.l12b12, 2, 3)
        self.grid.addLayout(self.l13b13, 3, 0)
        self.grid.addLayout(self.l14b14, 3, 1)
        self.grid.addLayout(self.l15b15, 3, 2)
        self.grid.addLayout(self.l16b16, 3, 3)
        self.grid.addLayout(self.l17b17, 4, 0)
        self.grid.addLayout(self.l18b18, 4, 1)
        self.grid.addLayout(self.l19b19, 4, 2)
        self.grid.addLayout(self.l20b20, 4, 3)
        self.grid.addLayout(self.l21b21, 5, 0)
        self.grid.addLayout(self.l22b22, 5, 1)
        self.grid.addLayout(self.l23b23, 5, 2)
        self.grid.addLayout(self.l24b24, 5, 3)
        self.setCentralWidget(self.group)
        
        
        
        
        self.setCentralWidget(self.group)
        
        
    def page(self):
        self.newpage = Interface()
        self.newpage.show()
        
def main():
    application = QApplication(sys.argv)
    mon_appli = Supervision()
    mon_appli.show()
    sys.exit(application.exec_())


if __name__== '__main__':
    main()
    
